"""fast.py - Optimized implementation of the finite SE-210 audit procedure.

This module computes the same result as the transparent oracle without
constructing identity relations as explicit sets of record pairs.

Declared and sibling identity classes are built from nonbreaking history
edges using union-find.
The implementation's operational classes are represented
directly by each record's identity-treatment signature.

Faithfulness, witness extraction, sibling-relative classification, and
regime substitution are then determined by examining labels within declared
record blocks.
No subset of the full Cartesian product ``R × R`` is materialized.

Agreement between this implementation and
:mod:`se_verification_operational_identity.oracle` provides the differential
check for the procedure described in Theorem 5.2.
"""

from collections.abc import Iterable, Mapping

from .model import (
    Instance,
    Kind,
    Record,
    Regime,
    Result,
    Verdict,
    nonbreaking_edges,
)


class _UnionFind:
    """Maintain disjoint record groups generated by nonbreaking history edges.

    Each record begins in its own group.
    Joining two records merges their groups,
    and finding a record returns the representative used as that
    group's label.

    Path compression shortens previously traversed parent chains so later
    lookups require less work.
    """

    def __init__(self, items: Iterable[Record]) -> None:
        """Create one singleton group for every supplied record."""
        self.parent: dict[Record, Record] = {x: x for x in items}

    def find(self, x: Record) -> Record:
        """Return the representative of the group containing ``x``.

        The first loop follows parent links to the current root.
        The second loop compresses the traversed path
        so those records point directly to that root.
        """
        root = x
        while self.parent[root] != root:
            root = self.parent[root]
        while self.parent[x] != root:  # path compression
            self.parent[x], x = root, self.parent[x]
        return root

    def union(self, a: Record, b: Record) -> None:
        """Merge the groups containing ``a`` and ``b``.

        Nothing changes when the two records already belong to the same
        group.
        """
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self.parent[rb] = ra


def labels(inst: Instance, regime: Regime) -> dict[Record, Record]:
    """Assign each record a label for its identity class under a regime.

    The function joins the endpoints of every history edge classified as
    nonbreaking by the supplied regime.
    Records connected through those edges receive
    the same union-find representative.

    Equality of the returned labels therefore indicates membership in the
    same declared identity class.
    """
    uf = _UnionFind(inst.records)
    for x, y in nonbreaking_edges(inst, regime):
        uf.union(x, y)
    return {r: uf.find(r) for r in inst.records}


def sig_labels(inst: Instance) -> dict[Record, tuple[object, ...]]:
    """Assign each record its complete identity-treatment signature.

    Records receive the same operational label exactly when every identified
    use of the surface produces the same outcome for both records.
    """
    return {r: inst.surface.signature(r) for r in inst.records}


def blocks(
    labels: Mapping[Record, object], records: Iterable[Record]
) -> list[list[Record]]:
    """Group records that carry the same supplied label.

    Each returned list represents one block of the partition induced by
    ``labels``.
    Record order within a block follows the order in which records
    are supplied.
    """
    groups: dict[object, list[Record]] = {}
    for r in records:
        groups.setdefault(labels[r], []).append(r)
    return list(groups.values())


def restricted_refines(
    block: list[Record], fine: Mapping[Record, object], coarse: Mapping[Record, object]
) -> bool:
    """Return whether ``fine`` refines ``coarse`` within one record block.

    Refinement holds when records sharing a fine label always share the same
    coarse label.
    The fine partition may make additional distinctions, but it
    may not merge records that the coarse partition separates.

    The check records the first coarse label observed for each fine label and
    returns ``False`` if a later record produces a conflicting coarse label.
    It therefore avoids enumerating every pair of records in the block.
    """
    seen: dict[object, object] = {}
    for r in block:
        f, c = fine[r], coarse[r]
        if f in seen:
            if seen[f] != c:
                return False
        else:
            seen[f] = c
    return True


def audit(inst: Instance) -> Result:
    """Audit one supplied instance using partition labels.

    The procedure first constructs labels for the declared identity classes
    and for the implementation's identity-treatment signatures.

    Faithfulness holds when every declared block has one operational
    signature.
    When a block contains different signatures, the first such
    pair is retained as a divergence witness.

    If no sibling regime is supplied, a failed audit is classified as
    unpositioned.
    Otherwise, the procedure constructs sibling labels and compares
    the operational and sibling partitions inside each declared
    block.

    Mutual refinement gives sibling alignment.
    Refinement in only one direction gives sub-sibling or
    super-sibling divergence, and refinement
    in neither direction gives sibling-incomparable divergence.

    Regime substitution is evaluated separately by comparing the complete
    operational and sibling partitions across the entire record domain.
    """
    tau = labels(inst, inst.tau)
    sig = sig_labels(inst)
    tau_blocks = blocks(tau, inst.records)

    # Faithfulness and witness: each declared block must be signature-homogeneous.
    witness: tuple[Record, Record] | None = None
    faithful = True
    for block in tau_blocks:
        anchor = block[0]
        for r in block[1:]:
            if sig[r] != sig[anchor]:
                faithful = False
                witness = (anchor, r)
                break
        if not faithful:
            break

    if faithful:
        return Result(Verdict.PASS, Kind.NONE, substitution=False, witness=None)

    if inst.sib is None:
        return Result(
            Verdict.FAIL, Kind.UNPOSITIONED, substitution=False, witness=witness
        )

    sib = labels(inst, inst.sib)

    # Regime substitution: pi_d == pi_sib on all of R. Compare the two
    # partitions by their block structure via a signature-block <-> sib-block
    # bijection check.
    substitution = _same_partition(sig, sib, inst.records)

    # Does the sibling split any declared block? Delta^sib != ~_tau iff some
    # declared block carries two distinct sibling labels.
    sib_splits = any(not block_homogeneous(block, sib) for block in tau_blocks)
    if not sib_splits:
        return Result(
            Verdict.FAIL, Kind.UNPOSITIONED, substitution=substitution, witness=witness
        )

    # Delta^op subset Delta^sib  <=>  within every declared block, the
    # signature partition refines the sibling partition. And symmetrically.
    op_sub_sib = all(restricted_refines(b, sig, sib) for b in tau_blocks)
    sib_sub_op = all(restricted_refines(b, sib, sig) for b in tau_blocks)

    if op_sub_sib and sib_sub_op:
        kind = Kind.ALIGNED
    elif op_sub_sib:
        kind = Kind.SUB
    elif sib_sub_op:
        kind = Kind.SUPER
    else:
        kind = Kind.INCOMPARABLE

    return Result(Verdict.FAIL, kind, substitution=substitution, witness=witness)


def block_homogeneous(block: list[Record], labels: Mapping[Record, object]) -> bool:
    """Return whether every record in a nonempty block has the same label.

    The first record supplies the comparison label.
    A differing label means the supplied partition splits the block.
    """
    anchor = labels[block[0]]
    return all(labels[r] == anchor for r in block)


def _same_partition(
    a: Mapping[Record, object], b: Mapping[Record, object], records: Iterable[Record]
) -> bool:
    """Return whether two label maps induce the same record partition.

    The concrete label values do not need to match.
    The partitions are equal when records share an ``a`` label
    exactly when they share a ``b`` label.

    This is checked as mutual refinement:
    ``a`` must refine ``b``, and ``b``
    must refine ``a``.
    """
    recs = list(records)
    a_ref_b = restricted_refines(recs, a, b)
    b_ref_a = restricted_refines(recs, b, a)
    return a_ref_b and b_ref_a
