"""oracle.py - Transparent reference checker for the SE-210 audit.

This module implements the paper's definitions directly using explicit sets
of ordered record pairs.
It serves as an independent reference against which
the optimized checker is compared.

Declared identity relations are constructed from the nonbreaking history
edges for a regime.
Their reflexive, symmetric, and transitive closure is
computed by repeatedly adding implied pairs until no more can be added.
The implementation deliberately does not share union-find or partition code
with :mod:`se_verification_operational_identity.fast`.

Faithfulness, refinement, sibling-relative classification, and regime
substitution are then evaluated using literal set containment and equality.
This approach is intentionally simple rather than efficient, making the
connection between the definitions in the paper and the executable checks
easy to inspect.
"""

from collections.abc import Iterable

from .model import (
    Instance,
    Kind,
    Record,
    Regime,
    Result,
    Verdict,
    nonbreaking_edges,
)

Relation = frozenset[tuple[Record, Record]]


def _closure(
    records: Iterable[Record], edges: Iterable[tuple[Record, Record]]
) -> Relation:
    """Return the equivalence relation generated by the supplied edges.

    Every record is first related to itself.
    Each supplied edge is added in both directions,
    and transitive consequences are added repeatedly until
    no new pairs can be found.

    The result is the smallest reflexive, symmetric, and transitive relation
    containing all supplied edges.
    """
    rs = list(records)
    pairs: set[tuple[Record, Record]] = {(r, r) for r in rs}
    for x, y in edges:
        pairs.add((x, y))
        pairs.add((y, x))
    # Naive transitive fixpoint.
    changed = True
    while changed:
        changed = False
        current = list(pairs)
        for a, b in current:
            for c, d in current:
                if b == c and (a, d) not in pairs:
                    pairs.add((a, d))
                    changed = True
    return frozenset(pairs)


def declared_relation(inst: Instance, regime: Regime) -> Relation:
    """Return the declared identity relation for a regime.

    History edges classified as identity-preserving by the regime are closed
    under reflexivity, symmetry, and transitivity.
    Two records occur in the returned relation exactly
    when the regime places them in the same declared identity class.

    This implements Definition 2.4.
    """
    return _closure(inst.records, nonbreaking_edges(inst, regime))


def treatment_relation(inst: Instance) -> Relation:
    """Return the identity relation induced by the implementation surface.

    Each record receives an identity-treatment signature from the supplied
    surface. Two records are related exactly when their complete signatures
    are equal.

    The returned relation therefore represents the operational partition
    induced by the surface and its identified uses.

    This implements Definition 3.11.
    """
    sig = {r: inst.surface.signature(r) for r in inst.records}
    return frozenset(
        (r, s) for r in inst.records for s in inst.records if sig[r] == sig[s]
    )


def refines(fine: Relation, coarse: Relation) -> bool:
    """Return whether the first relation refines the second.

    A finer partition may separate records that the coarser partition merges,
    but it may not merge records that the coarser partition separates.
    Equivalently, every pair related by ``fine``
    must also be related by ``coarse``.
    """
    return fine <= coarse


def find_witness(
    tau_rel: Relation, treat: Relation, records: tuple[Record, ...]
) -> tuple[Record, Record] | None:
    """Return a concrete witness that the implementation is not faithful.

    A divergence witness is a pair of records that the declared regime treats
    as the same but the implementation surface treats as different.

    Records are examined in their supplied order. The first witness found is
    returned, or None when no such pair exists.

    This implements Definition 4.3.
    """
    for r in records:
        for s in records:
            if (r, s) in tau_rel and (r, s) not in treat:
                return (r, s)
    return None


def audit(inst: Instance) -> Result:
    """Audit one supplied instance using paper definitions literally.

    The audit first compares the declared identity relation with the
    implementation treatment relation.
    It passes when the implementation
    does not split any declared identity class.

    When faithfulness fails, the result includes a concrete divergence
    witness.

    If no sibling regime is available, the divergence is classified
    as unpositioned.

    Otherwise, the implementation and sibling relations are
    restricted to pairs inside the declared classes
    and compared by literal set containment.

    The two containment results determine whether the divergence is
    sibling-aligned, sub-sibling, super-sibling, or sibling-incomparable.

    Regime substitution is reported separately and holds only when the
    implementation relation equals the sibling relation across the entire
    record domain.
    """
    tau_rel = declared_relation(inst, inst.tau)
    treat = treatment_relation(inst)

    # Faithfulness, Definition 4.1: pi_tau refines pi_d, i.e. ~_tau subset ~=_d.
    faithful = refines(tau_rel, treat)
    if faithful:
        return Result(Verdict.PASS, Kind.NONE, substitution=False, witness=None)

    witness = find_witness(tau_rel, treat, inst.records)

    if inst.sib is None:
        return Result(
            Verdict.FAIL, Kind.UNPOSITIONED, substitution=False, witness=witness
        )

    sib_rel = declared_relation(inst, inst.sib)

    # Delta^op_d and Delta^sib, Definition 4.7 (both intersected with ~_tau).
    delta_op = frozenset(p for p in treat if p in tau_rel)
    delta_sib = frozenset(p for p in sib_rel if p in tau_rel)

    # Regime substitution, Definition 4.10: ~=_d == ~_sib on all of R.
    substitution = treat == sib_rel

    # Unpositioned when the sibling makes no extra split inside declared classes.
    if delta_sib == tau_rel:
        return Result(
            Verdict.FAIL, Kind.UNPOSITIONED, substitution=substitution, witness=witness
        )

    op_sub_sib = delta_op <= delta_sib
    sib_sub_op = delta_sib <= delta_op
    if op_sub_sib and sib_sub_op:
        kind = Kind.ALIGNED
    elif op_sub_sib:
        kind = Kind.SUB
    elif sib_sub_op:
        kind = Kind.SUPER
    else:
        kind = Kind.INCOMPARABLE

    return Result(Verdict.FAIL, kind, substitution=substitution, witness=witness)
